os: osx

language: node_js
node_js:
  - node

sudo: required

services:
  - docker

compiler:
  - clang

script:
  - export MRUBY_CONFIG="../../tools/mruby-patcher/build_config.host.rb"
  - make mruby
  - make