#os: osx
os: linux

language: node_js
node_js:
  - node

sudo: required

services:
  - docker

compiler:
  - clang

before_install:
  - docker build --no-cache -t emscripten:mqrb .
  - docker run -dit --name emscripten -v $(pwd):/src emscripten:mqrb bash

script:
#  - export MRUBY_CONFIG="../../tools/mruby-patcher/build_config.host.rb"
#  - make mruby
#  - make
#  - export MRUBY_CONFIG="../../tools/mruby-patcher/build_config.wasm.rb"
  - docker exec -it -e MRUBY_CONFIG="../../tools/mruby-patcher/build_config.wasm.rb" emscripten make wasm-production

branches:
  only:
  - master
  - stable
  - ci-test